package gui;


import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DISTRIEMPAQUES
 */
public class menuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menuPrincipal.class.getName());

    /**
     * Creates new form menuPrincipal
     */
    private int idUsuario;

public menuPrincipal(int idUsuario, String nombreRecibido) {

    this.idUsuario = idUsuario;

    util.SesionUsuario.setIdUsuario(idUsuario);

    initComponents();

    cargarIconos();
    icono_entrarp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

icono_entrarp.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        abrirPerfil();
    }
});

    this.setSize(1280, 720);

    this.setLocationRelativeTo(null);

    lbl_bienvenida.setText(
            "¡Bienvenido, " + nombreRecibido + "!"
    );

    lbl_nomreS.setText(nombreRecibido);

    
    

    
     

    // CLICK EN CERRAR SESIÓN
    label_cerrarS.setCursor(
            new java.awt.Cursor(
                    java.awt.Cursor.HAND_CURSOR
            )
    );

    label_cerrarS.addMouseListener(
            new java.awt.event.MouseAdapter() {

                @Override
                public void mouseClicked(
                        java.awt.event.MouseEvent evt
                ) {

                    cerrarSesion();
                }
            }
    );
}
 public menuPrincipal(String nombreRecibido) {

        initComponents();
        cargarIconos();

        this.setSize(1280, 720);
        this.setLocationRelativeTo(null);

        lbl_bienvenida.setText("¡Bienvenido, " + nombreRecibido + "!");
        lbl_nomreS.setText(nombreRecibido);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                try {
                    String ruta = "C:\\Users\\DISTRIEMPAQUES\\Desktop\\Pro de aula - Tecer Semestre\\ProyectodeAula\\fondo (2).png";
                    java.io.File archivo = new java.io.File(ruta);
                    if (archivo.exists()) {
                        java.awt.Image img = javax.imageio.ImageIO.read(archivo);
                        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                    }
                } catch (Exception e) { e.printStackTrace(); }
            }
        };
        panel_azul = new javax.swing.JPanel();
        txt_info = new javax.swing.JLabel();
        txt_info1 = new javax.swing.JLabel();
        label_nombre1 = new javax.swing.JLabel();
        label_rol = new javax.swing.JLabel();
        label_cerrarS = new javax.swing.JLabel();
        lbl_nomreS = new javax.swing.JLabel();
        lbl_rol = new javax.swing.JLabel();
        label_volverMenuPrincipal = new javax.swing.JLabel();
        tarjeta_1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                // Activamos el suavizado de bordes (Anti-aliasing)
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Dibujamos el fondo blanco redondeado
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // 30 es el nivel de redondeo

                // Dibujamos el borde gris muy clarito (opcional, para que resalte)
                g2.setColor(new java.awt.Color(230, 230, 230));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
            }
        };
        txt_info3 = new javax.swing.JLabel();
        txt_info4 = new javax.swing.JLabel();
        txt_info5 = new javax.swing.JLabel();
        circulo1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Color azul muy clarito (como el de la referencia)
                g2.setColor(new java.awt.Color(232, 240, 254)); 

                // Dibujamos el círculo (un óvalo con mismo ancho y alto)
                g2.fillOval(0, 0, getWidth(), getHeight());
            }
        };
        icono_voto = new javax.swing.JLabel();
        ícono_entrarv = new javax.swing.JLabel();
        tarjeta_2 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                // Activamos el suavizado de bordes (Anti-aliasing)
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Dibujamos el fondo blanco redondeado
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // 30 es el nivel de redondeo

                // Dibujamos el borde gris muy clarito (opcional, para que resalte)
                g2.setColor(new java.awt.Color(230, 230, 230));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
            }
        };
        txt_info6 = new javax.swing.JLabel();
        txt_info7 = new javax.swing.JLabel();
        txt_info8 = new javax.swing.JLabel();
        circulo2 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Color azul muy clarito (como el de la referencia)
                g2.setColor(new java.awt.Color(232, 240, 254)); 

                // Dibujamos el círculo (un óvalo con mismo ancho y alto)
                g2.fillOval(0, 0, getWidth(), getHeight());
            }
        };
        icono_info = new javax.swing.JLabel();
        icono_entrare = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tarjeta_3 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                // Activamos el suavizado de bordes (Anti-aliasing)
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Dibujamos el fondo blanco redondeado
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // 30 es el nivel de redondeo

                // Dibujamos el borde gris muy clarito (opcional, para que resalte)
                g2.setColor(new java.awt.Color(230, 230, 230));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
            }
        };
        txt_info9 = new javax.swing.JLabel();
        txt_info10 = new javax.swing.JLabel();
        txt_info11 = new javax.swing.JLabel();
        circulo3 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Color azul muy clarito (como el de la referencia)
                g2.setColor(new java.awt.Color(232, 240, 254)); 

                // Dibujamos el círculo (un óvalo con mismo ancho y alto)
                g2.fillOval(0, 0, getWidth(), getHeight());
            }
        };
        icono_perfil = new javax.swing.JLabel();
        icono_entrarp = new javax.swing.JLabel();
        panel_footer = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Color azul pálido de la imagen
                g2.setColor(new java.awt.Color(240, 247, 255)); 
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 25, 25);

                // Borde sutil
                g2.setColor(new java.awt.Color(220, 230, 240));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 25, 25);
            }
        };
        panel_circulo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Color azul muy clarito (como el de la referencia)
                g2.setColor(new java.awt.Color(232, 240, 254)); 

                // Dibujamos el círculo (un óvalo con mismo ancho y alto)
                g2.fillOval(0, 0, getWidth(), getHeight());
            }
        };
        txt_estado = new javax.swing.JLabel();
        txt_info14 = new javax.swing.JLabel();
        txt_info15 = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        panel_circulo2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panel_circulo3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_bienvenida = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_decoracion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_fondo.setMaximumSize(new java.awt.Dimension(1280, 720));
        panel_fondo.setMinimumSize(new java.awt.Dimension(1280, 720));
        panel_fondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        panel_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_azul.setBackground(new java.awt.Color(0, 74, 173));
        panel_azul.setMaximumSize(new java.awt.Dimension(1280, 90));
        panel_azul.setMinimumSize(new java.awt.Dimension(1280, 90));
        panel_azul.setPreferredSize(new java.awt.Dimension(1280, 90));
        panel_azul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_info.setForeground(new java.awt.Color(255, 255, 255));
        txt_info.setText("Sistema de votaciones");
        panel_azul.add(txt_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 203, 32));

        txt_info1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info1.setForeground(new java.awt.Color(255, 255, 255));
        txt_info1.setText("Sistema universitario");
        panel_azul.add(txt_info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        label_nombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_nombre1.setForeground(new java.awt.Color(255, 255, 255));
        panel_azul.add(label_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 190, 40));

        label_rol.setForeground(new java.awt.Color(255, 255, 255));
        panel_azul.add(label_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 130, 30));

        label_cerrarS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_cerrarS.setForeground(new java.awt.Color(255, 255, 255));
        label_cerrarS.setText("Cerrar sesión");
        panel_azul.add(label_cerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 80, 40));

        lbl_nomreS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_nomreS.setForeground(new java.awt.Color(255, 255, 255));
        panel_azul.add(lbl_nomreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 180, 30));

        lbl_rol.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rol.setText("\n");
        panel_azul.add(lbl_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 110, 30));

        label_volverMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_volverMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        label_volverMenuPrincipal.setText("<- Volver");
        label_volverMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_volverMenuPrincipalMouseClicked(evt);
            }
        });
        panel_azul.add(label_volverMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, -1));

        panel_fondo.add(panel_azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tarjeta_1.setBackground(new java.awt.Color(255, 255, 255));
        tarjeta_1.setOpaque(false);
        tarjeta_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_info3.setForeground(new java.awt.Color(0, 74, 173));
        txt_info3.setText("VOTAR");
        txt_info3.setToolTipText("");
        tarjeta_1.add(txt_info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        txt_info4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info4.setText("Participa en las votaciones disponibles ");
        tarjeta_1.add(txt_info4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, 30));

        txt_info5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info5.setText("y elige tu opción.");
        tarjeta_1.add(txt_info5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 180, 20));

        circulo1.setOpaque(false);

        icono_voto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono_voto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icono_votoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout circulo1Layout = new javax.swing.GroupLayout(circulo1);
        circulo1.setLayout(circulo1Layout);
        circulo1Layout.setHorizontalGroup(
            circulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono_voto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        circulo1Layout.setVerticalGroup(
            circulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono_voto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tarjeta_1.add(circulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 100));

        ícono_entrarv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ícono_entrarv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voto(evt);
            }
        });
        tarjeta_1.add(ícono_entrarv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 100));

        panel_fondo.add(tarjeta_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 320, 380));

        tarjeta_2.setBackground(new java.awt.Color(255, 255, 255));
        tarjeta_2.setOpaque(false);
        tarjeta_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_info6.setForeground(new java.awt.Color(0, 74, 173));
        txt_info6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info6.setText("Estado de votación");
        tarjeta_2.add(txt_info6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 30));

        txt_info7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info7.setText("Verifica que ya has votado y consulta");
        tarjeta_2.add(txt_info7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, 20));

        txt_info8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info8.setText("las votaciones disponibles.");
        tarjeta_2.add(txt_info8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 180, -1));

        circulo2.setOpaque(false);

        icono_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout circulo2Layout = new javax.swing.GroupLayout(circulo2);
        circulo2.setLayout(circulo2Layout);
        circulo2Layout.setHorizontalGroup(
            circulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circulo2Layout.createSequentialGroup()
                .addComponent(icono_info, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        circulo2Layout.setVerticalGroup(
            circulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circulo2Layout.createSequentialGroup()
                .addComponent(icono_info, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tarjeta_2.add(circulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 100));

        icono_entrare.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tarjeta_2.add(icono_entrare, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 100));

        jPanel2.setBackground(new java.awt.Color(0, 74, 173));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        tarjeta_2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 120, 4));

        panel_fondo.add(tarjeta_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 320, 380));

        tarjeta_3.setBackground(new java.awt.Color(255, 255, 255));
        tarjeta_3.setOpaque(false);
        tarjeta_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_info9.setForeground(new java.awt.Color(0, 74, 173));
        txt_info9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info9.setText("Ver perfil");
        tarjeta_3.add(txt_info9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 30));

        txt_info10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info10.setText("Consulta y actualiza tu información");
        tarjeta_3.add(txt_info10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txt_info11.setText("personal y datos de cuenta.");
        tarjeta_3.add(txt_info11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        circulo3.setOpaque(false);

        icono_perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout circulo3Layout = new javax.swing.GroupLayout(circulo3);
        circulo3.setLayout(circulo3Layout);
        circulo3Layout.setHorizontalGroup(
            circulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        circulo3Layout.setVerticalGroup(
            circulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        tarjeta_3.add(circulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 100));

        icono_entrarp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tarjeta_3.add(icono_entrarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 100));

        panel_fondo.add(tarjeta_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 320, 380));

        panel_footer.setOpaque(false);
        panel_footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_circulo.setOpaque(false);

        javax.swing.GroupLayout panel_circuloLayout = new javax.swing.GroupLayout(panel_circulo);
        panel_circulo.setLayout(panel_circuloLayout);
        panel_circuloLayout.setHorizontalGroup(
            panel_circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panel_circuloLayout.setVerticalGroup(
            panel_circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panel_footer.add(panel_circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 60));

        txt_estado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_estado.setForeground(new java.awt.Color(0, 74, 173));
        txt_estado.setText("Estado actual");
        panel_footer.add(txt_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 25, -1, -1));

        txt_info14.setForeground(new java.awt.Color(102, 102, 102));
        txt_info14.setText("Aquí puedes ver un resumen ");
        panel_footer.add(txt_info14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, -1, -1));

        txt_info15.setForeground(new java.awt.Color(102, 102, 102));
        txt_info15.setText("de tu actividad en el sistema.");
        panel_footer.add(txt_info15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 58, -1, -1));

        separador.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel_footer.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 20, 20, 60));

        panel_circulo2.setOpaque(false);

        javax.swing.GroupLayout panel_circulo2Layout = new javax.swing.GroupLayout(panel_circulo2);
        panel_circulo2.setLayout(panel_circulo2Layout);
        panel_circulo2Layout.setHorizontalGroup(
            panel_circulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panel_circulo2Layout.setVerticalGroup(
            panel_circulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panel_footer.add(panel_circulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 60, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Estado de votación");
        panel_footer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 25, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panel_footer.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 30, 60));

        panel_circulo3.setOpaque(false);

        javax.swing.GroupLayout panel_circulo3Layout = new javax.swing.GroupLayout(panel_circulo3);
        panel_circulo3.setLayout(panel_circulo3Layout);
        panel_circulo3Layout.setHorizontalGroup(
            panel_circulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        panel_circulo3Layout.setVerticalGroup(
            panel_circulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panel_footer.add(panel_circulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 60, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Proximas votaciones");
        panel_footer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 25, -1, -1));

        panel_fondo.add(panel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 1040, 100));

        lbl_bienvenida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_bienvenida.setText("¡Bienvenido!, ");
        panel_fondo.add(lbl_bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Selecciona una opción para continuar");
        panel_fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 155, 210, -1));

        panel_decoracion.setBackground(new java.awt.Color(0, 74, 173));

        javax.swing.GroupLayout panel_decoracionLayout = new javax.swing.GroupLayout(panel_decoracion);
        panel_decoracion.setLayout(panel_decoracionLayout);
        panel_decoracionLayout.setHorizontalGroup(
            panel_decoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        panel_decoracionLayout.setVerticalGroup(
            panel_decoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        panel_fondo.add(panel_decoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 120, 4));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        panel_fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 80, 80));

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        panel_fondo.add(panelCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1190, 570));

        getContentPane().add(panel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voto(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voto
        // TODO add your handling code here:
        PanelSeleccionEleccion panel = new PanelSeleccionEleccion(this);
        panel.cargarElecciones();
        mostrarPanel(panel);
    }//GEN-LAST:event_voto

    private void icono_votoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icono_votoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icono_votoMouseClicked

    private void label_volverMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_volverMenuPrincipalMouseClicked
        // Label para volver a menu principal

        restaurarMenuPrincipal();
    }//GEN-LAST:event_label_volverMenuPrincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {new menuPrincipal(1, "Usuario de Prueba").setVisible(true);  });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel circulo1;
    private javax.swing.JPanel circulo2;
    private javax.swing.JPanel circulo3;
    private javax.swing.JLabel icono_entrare;
    private javax.swing.JLabel icono_entrarp;
    private javax.swing.JLabel icono_info;
    private javax.swing.JLabel icono_perfil;
    private javax.swing.JLabel icono_voto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_cerrarS;
    private javax.swing.JLabel label_nombre1;
    private javax.swing.JLabel label_rol;
    private javax.swing.JLabel label_volverMenuPrincipal;
    private javax.swing.JLabel lbl_bienvenida;
    private javax.swing.JLabel lbl_nomreS;
    private javax.swing.JLabel lbl_rol;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panel_azul;
    private javax.swing.JPanel panel_circulo;
    private javax.swing.JPanel panel_circulo2;
    private javax.swing.JPanel panel_circulo3;
    private javax.swing.JPanel panel_decoracion;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JPanel panel_footer;
    private javax.swing.JSeparator separador;
    private javax.swing.JPanel tarjeta_1;
    private javax.swing.JPanel tarjeta_2;
    private javax.swing.JPanel tarjeta_3;
    private javax.swing.JLabel txt_estado;
    private javax.swing.JLabel txt_info;
    private javax.swing.JLabel txt_info1;
    private javax.swing.JLabel txt_info10;
    private javax.swing.JLabel txt_info11;
    private javax.swing.JLabel txt_info14;
    private javax.swing.JLabel txt_info15;
    private javax.swing.JLabel txt_info3;
    private javax.swing.JLabel txt_info4;
    private javax.swing.JLabel txt_info5;
    private javax.swing.JLabel txt_info6;
    private javax.swing.JLabel txt_info7;
    private javax.swing.JLabel txt_info8;
    private javax.swing.JLabel txt_info9;
    private javax.swing.JLabel ícono_entrarv;
    // End of variables declaration//GEN-END:variables


private ImageIcon cargarIcono(String nombre, int ancho, int alto) {
    String base = System.getProperty("user.dir");

    ImageIcon icono = new ImageIcon(base + "\\" + nombre);

    Image img = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

    return new ImageIcon(img);
}
private void cargarIconos() {
    icono_voto.setIcon(cargarIcono("voto.png", 100, 100));
    icono_info.setIcon(cargarIcono("info.png", 100, 100));
    icono_perfil.setIcon(cargarIcono("usuario.png", 100, 100));
    ícono_entrarv.setIcon(cargarIcono("user blanco (2).png", 100, 100));
    icono_entrare.setIcon(cargarIcono("user blanco (2).png", 100, 100));
    icono_entrarp.setIcon(cargarIcono("user blanco (2).png", 100, 100));
    

}

private void abrirPerfil() {

    tarjeta_1.setVisible(false);

    tarjeta_2.setVisible(false);

    tarjeta_3.setVisible(false);

    panel_footer.setVisible(false);

    lbl_bienvenida.setVisible(false);

    jLabel3.setVisible(false);

    panel_decoracion.setVisible(false);

    mostrarPanel(new gui.PanelPerfil(this));
}

public void restaurarMenuPrincipal() {

    panelCentral.removeAll();

    panelCentral.setVisible(false);

    tarjeta_1.setVisible(true);
    tarjeta_2.setVisible(true);
    tarjeta_3.setVisible(true);

    panel_footer.setVisible(true);

    lbl_bienvenida.setVisible(true);

    jLabel3.setVisible(true);

    panel_decoracion.setVisible(true);

    panel_fondo.revalidate();
    panel_fondo.repaint();
}


private void cerrarSesion() {

    int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Deseas cerrar sesión?",
            "Cerrar sesión",
            JOptionPane.YES_NO_OPTION
    );

    if (opcion == JOptionPane.YES_OPTION) {

        dispose();

        new login().setVisible(true);
    }
}

public void mostrarPanel(Component panel) {

    panelCentral.removeAll();

    panelCentral.setVisible(true);

    panelCentral.setLayout(new BorderLayout());

    panelCentral.add(panel, BorderLayout.CENTER);

    panel_fondo.setComponentZOrder(panelCentral, 0);

    panelCentral.revalidate();

    panelCentral.repaint();
}
}


