/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import config.Conexion;
import java.awt.BorderLayout;
import java.awt.Image;
import static java.awt.SystemColor.menu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;

/**
 *
 * @author DISTRIEMPAQUES
 */
public class PanelSeleccionEleccion extends javax.swing.JPanel {

    /**
     * Creates new form PanelSeleccionEleccion
     */
    private javax.swing.JList<String> lista;
    private javax.swing.JScrollPane scrollLista; // Necesario para que la lista se vea bien
    private List<Integer> ids = new ArrayList<>();
private List<String> nombres = new ArrayList<>();
     private menuPrincipal menu;
     
    public PanelSeleccionEleccion(menuPrincipal menu) {
        initComponents();
        this.menu = menu;
        initCustomComponents();
        cargarElecciones();
        initEventos();  
    }
    
    private void initCustomComponents() {
        // 3. Instanciar (Crear el objeto)
        lista = new javax.swing.JList<>();
        scrollLista = new javax.swing.JScrollPane(lista);

        // 4. Configurar posición en el AbsoluteLayout
        // (x, y, ancho, alto) -> Ajusta estos valores a tu gusto
        this.add(scrollLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 400, 250));
        
        // Esto fuerza al panel a mostrar lo que acabamos de agregar
        this.revalidate();
        this.repaint();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 74, 173));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccionar una elección");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 110));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
  public void cargarElecciones() {
  DefaultListModel<String> modelo = new DefaultListModel<>();
        ids.clear();

        try (Connection con = Conexion.conectar()) {
            String sql = "SELECT id_eleccion, nombre FROM elecciones WHERE estado_activa = 1";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id_eleccion");
                String nombre = rs.getString("nombre");
                ids.add(id);
                modelo.addElement(id + " - " + nombre);
            }

            lista.setModel(modelo);

            // Redirección automática si solo hay una
            if (ids.size() == 1) {
                SwingUtilities.invokeLater(() -> abrirCandidatos(ids.get(0)));
            }

        } catch (Exception e) {
            // Aquí te saldrá el "Communications link failure" si XAMPP está apagado
            JOptionPane.showMessageDialog(this, "Error de conexión: " + e.getMessage());
        }
    }

    private void initEventos() {
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    seleccionarEleccion();
                }
            }
        });
    }

    private void seleccionarEleccion() {
        int index = lista.getSelectedIndex();
        if (index != -1) {
            abrirCandidatos(ids.get(index));
        }
    }

    private void abrirCandidatos(int idEleccion) {
        PanelCandidatos panel = new PanelCandidatos();
        panel.cargarCandidatos(idEleccion);
        if (menu != null) {
            menu.mostrarPanel(panel);
        }
    }
}
