/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import config.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author DISTRIEMPAQUES
 */
public class PanelCandidatos extends javax.swing.JPanel {

    /**
     * Creates new form PanelCandidatos
     */
    public PanelCandidatos() {
        initComponents();
        System.out.println("PANEL CANDIDATOS CREADO");
this.setBackground(java.awt.Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
     public void cargarCandidatos(int idEleccion) {
         System.out.println("CARGANDO CANDIDATOS: " + idEleccion);

       try {
        Connection con = Conexion.conectar();

        String sql = "SELECT * FROM candidatos WHERE id_eleccion = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, idEleccion);

        ResultSet rs = ps.executeQuery();

        this.removeAll();
        this.removeAll();
this.setLayout(new java.awt.GridLayout(0, 2));

        while (rs.next()) {

            String nombre = rs.getString("nombre");
            String carrera = rs.getString("carrera");
            String foto = rs.getString("foto");

            CardCandidato card = new CardCandidato(nombre, carrera, foto, rs.getInt("id_candidato"));

            this.add(card);
            System.out.println("CANDIDATO: " + nombre);
        }

        this.revalidate();
        this.repaint();

    } catch (Exception e) {
        System.out.println("ERROR: " + e.getMessage());
    }
     }
}
