package gui.auth;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DISTRIEMPAQUES
 */
import config.Conexion;
import dao.UsuarioBD;
import gui.admin.menuAdmin;
import gui.menuPrincipal;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.opencv.core.Mat;
import org.opencv.imgcodecs.Imgcodecs;
import util.placeHolderJtext;
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        cargarIconos();
        placeHolderJtext.addPlaceholder(caja_usuario, "INGRESE SU USUARIO");
        placeHolderJtext.addPlaceholderPassword(caja_contraseña, "Contraseña");
        // Limpiar campos al hacer click
caja_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusGained(java.awt.event.FocusEvent e) {
        if (caja_usuario.getText().equals("Usuario")) {
            caja_usuario.setText("");
        }
    }
    @Override
    public void focusLost(java.awt.event.FocusEvent e) {
        if (caja_usuario.getText().isEmpty()) {
            caja_usuario.setText("Usuario");
        }
    }
});

caja_contraseña.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusGained(java.awt.event.FocusEvent e) {
        if (new String(caja_contraseña.getPassword()).equals("******")) {
            caja_contraseña.setText("");
            caja_contraseña.setEchoChar('•');
        }
    }
    @Override 
    public void focusLost(java.awt.event.FocusEvent e) {
        if (caja_contraseña.getPassword().length == 0) {
            caja_contraseña.setEchoChar((char) 0);
            caja_contraseña.setText("******");
            
        }
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pa_fondo = new javax.swing.JPanel();
        pa_imagen = new javax.swing.JPanel();
        txt_info4 = new javax.swing.JLabel();
        txt_info5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ima_label = new javax.swing.JLabel();
        pa_info = new javax.swing.JPanel();
        txt_info = new javax.swing.JLabel();
        txt_info2 = new javax.swing.JLabel();
        caja_usuario = new javax.swing.JTextField();
        icono_3 = new javax.swing.JLabel();
        caja_contraseña = new javax.swing.JPasswordField();
        label_olvidasteContraseña = new javax.swing.JLabel();
        bt_inicio = new javax.swing.JButton();
        bt_face = new javax.swing.JButton();
        txt_info3 = new javax.swing.JLabel();
        label_registro = new javax.swing.JLabel();
        icono_1 = new javax.swing.JLabel();
        icono_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pa_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pa_imagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_info4.setForeground(new java.awt.Color(255, 255, 255));
        txt_info4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info4.setText("Sistema Universitario.");
        pa_imagen.add(txt_info4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 230, 50));

        txt_info5.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        txt_info5.setForeground(new java.awt.Color(255, 255, 255));
        txt_info5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info5.setText("VOTACIONES");
        pa_imagen.add(txt_info5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 280, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 247, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tu voto es importante.");
        pa_imagen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 270, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 247, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tu elección, nuestro futuro.");
        pa_imagen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 320, -1));

        ima_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ima_label.setToolTipText("");
        pa_imagen.add(ima_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pa_fondo.add(pa_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 720));

        pa_info.setBackground(new java.awt.Color(255, 255, 255));
        pa_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        txt_info.setForeground(new java.awt.Color(10, 25, 49));
        txt_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info.setText("INICIAR SESIÓN");
        pa_info.add(txt_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 38, 309, -1));

        txt_info2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txt_info2.setForeground(new java.awt.Color(102, 102, 102));
        txt_info2.setText("Ingresa tus credenciales para continuar.");
        pa_info.add(txt_info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 290, 30));

        caja_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        caja_usuario.setForeground(new java.awt.Color(24, 90, 219));
        caja_usuario.setText("Usuario");
        caja_usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(24, 90, 219)));
        pa_info.add(caja_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 410, 60));
        pa_info.add(icono_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 70, 50));

        caja_contraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        caja_contraseña.setForeground(new java.awt.Color(24, 90, 219));
        caja_contraseña.setText("******");
        caja_contraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(24, 90, 219)));
        caja_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_contraseñaActionPerformed(evt);
            }
        });
        pa_info.add(caja_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 410, 70));

        label_olvidasteContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_olvidasteContraseña.setForeground(new java.awt.Color(24, 90, 219));
        label_olvidasteContraseña.setText("¿Olvidaste tu contraseña?");
        label_olvidasteContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_olvidasteContraseñaMouseClicked(evt);
            }
        });
        pa_info.add(label_olvidasteContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 150, 30));

        bt_inicio.setBackground(new java.awt.Color(24, 90, 219));
        bt_inicio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt_inicio.setForeground(new java.awt.Color(255, 255, 255));
        bt_inicio.setText("Iniciar Sesión");
        bt_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrada(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salida(evt);
            }
        });
        bt_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inicioActionPerformed(evt);
            }
        });
        pa_info.add(bt_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 280, 70));

        bt_face.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bt_face.setForeground(new java.awt.Color(24, 90, 219));
        bt_face.setText("Face Id");
        bt_face.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 90, 219), 2, true));
        bt_face.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_faceActionPerformed(evt);
            }
        });
        pa_info.add(bt_face, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 280, 70));

        txt_info3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info3.setForeground(new java.awt.Color(102, 102, 102));
        txt_info3.setText("¿No tienes cuenta?");
        pa_info.add(txt_info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, 120, -1));

        label_registro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_registro.setForeground(new java.awt.Color(24, 90, 219));
        label_registro.setText("Registrarme");
        label_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_registroMouseClicked(evt);
            }
        });
        pa_info.add(label_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 650, 90, -1));
        pa_info.add(icono_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, 70));
        pa_info.add(icono_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 60, 60));

        pa_fondo.add(pa_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 780, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pa_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pa_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrada(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrada
        // TODO add your handling code here
        bt_inicio.setBackground(new Color(18, 69, 169));
    }//GEN-LAST:event_entrada

    private void salida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salida
        // TODO add your handling code here:
        bt_inicio.setBackground(new Color(24, 90, 219));
    }//GEN-LAST:event_salida

    private void bt_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inicioActionPerformed
        

//Boton de Login
        

        String usuario = caja_usuario.getText().trim();
    String password = new String(caja_contraseña.getPassword()).trim();
    
    
if (password.equals("******")) {
    JOptionPane.showMessageDialog(null, "Ingresa tu contraseña");
    return;
}

    if (usuario.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos");
        return;
    }

    if (password.length() < 4) {
        JOptionPane.showMessageDialog(null, "La contraseña es muy corta");
        return;
    }

    // 2. Comunicación con la base de datos
    UsuarioBD dao = new UsuarioBD();
    
    // Usaremos obtenerRol para manejar la redirección de menús
    String rol = dao.obtenerRol(usuario, password);

    if (rol != null) {
    JOptionPane.showMessageDialog(null, "¡Bienvenido " + usuario + "!");
    if (rol.equalsIgnoreCase("admin")) {
        menuAdmin mAdmin = new menuAdmin(usuario);
        mAdmin.setVisible(true);
    } else {
        // Obtener el ID del usuario para pasarlo al menuPrincipal
        int idUsuario = dao.obtenerIdPorUsuario(usuario, password);
        menuPrincipal mPrincipal = new menuPrincipal(idUsuario, usuario);
        mPrincipal.setVisible(true);
    }
    this.dispose();
} else {
    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
}

    }//GEN-LAST:event_bt_inicioActionPerformed

    private void bt_faceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_faceActionPerformed
    String correo = JOptionPane.showInputDialog(null, "Ingresa tu correo:");

    if (correo == null || correo.trim().isEmpty()) {

        JOptionPane.showMessageDialog(null, "Debes ingresar un correo");

        return;
    }

    correo = correo.trim().toLowerCase();

    UsuarioBD dao = new UsuarioBD();

    int idUsuario = dao.obtenerIdPorCorreo(correo);

    if (idUsuario != -1) {

        String nombre = dao.obtenerNombrePorCorreo(correo);

        new VentanaLoginFace(idUsuario, correo, nombre).setVisible(true);

        this.dispose();

    } else {

        JOptionPane.showMessageDialog(null, "Usuario no encontrado");
    }
       
    }//GEN-LAST:event_bt_faceActionPerformed

    private void label_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_registroMouseClicked
        // Label para mandar a registro
        
        registro r = new registro();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_label_registroMouseClicked

    private void label_olvidasteContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_olvidasteContraseñaMouseClicked
        // Label para cambiar contraseña
        
        recuperarContraseña();
    }//GEN-LAST:event_label_olvidasteContraseñaMouseClicked

    private void caja_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_contraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_face;
    private javax.swing.JButton bt_inicio;
    private javax.swing.JPasswordField caja_contraseña;
    private javax.swing.JTextField caja_usuario;
    private javax.swing.JLabel icono_1;
    private javax.swing.JLabel icono_2;
    private javax.swing.JLabel icono_3;
    private javax.swing.JLabel ima_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label_olvidasteContraseña;
    private javax.swing.JLabel label_registro;
    private javax.swing.JPanel pa_fondo;
    private javax.swing.JPanel pa_imagen;
    private javax.swing.JPanel pa_info;
    private javax.swing.JLabel txt_info;
    private javax.swing.JLabel txt_info2;
    private javax.swing.JLabel txt_info3;
    private javax.swing.JLabel txt_info4;
    private javax.swing.JLabel txt_info5;
    // End of variables declaration//GEN-END:variables
private ImageIcon cargarIcono(String nombre, int ancho, int alto) {
    String base = System.getProperty("user.dir");

    ImageIcon icono = new ImageIcon(base + "\\" + nombre);

    Image img = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

    return new ImageIcon(img);
}
private void cargarIconos() {
    icono_1.setIcon(cargarIcono("user.png", 32, 32));
    icono_2.setIcon(cargarIcono("contraseña.png", 32, 32));
    icono_3.setIcon(cargarIcono("ojo(1).png", 32, 32));
    ima_label.setIcon(cargarIcono("bueno.png", 500, 720));
    
}

private void recuperarContraseña() {

    String correo = JOptionPane.showInputDialog(
            this,
            "Ingresa tu correo:"
    );

    if (correo == null || correo.trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Debes ingresar un correo"
        );

        return;
    }

    UsuarioBD dao = new UsuarioBD();

    int idUsuario = dao.obtenerIdPorCorreo(correo);

    if (idUsuario == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Correo no encontrado"
        );

        return;
    }

    RecuperarFace ventana = new RecuperarFace(idUsuario, correo, correo);

    ventana.setVisible(true);
}
}
