package com.mycompany.proyectodeaula;


import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DISTRIEMPAQUES
 */
public class menuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menuPrincipal.class.getName());

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
        cargarIconos();
        this.setSize(1280, 720);
this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fondo = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                try {
                    String ruta = "C:\\Users\\DISTRIEMPAQUES\\Desktop\\Pro de aula - Tecer Semestre\\ProyectodeAula\\fondo (2).png";
                    java.io.File archivo = new java.io.File(ruta);
                    if (archivo.exists()) {
                        java.awt.Image img = javax.imageio.ImageIO.read(archivo);
                        g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
                    }
                } catch (Exception e) { e.printStackTrace(); }
            }
        };
        panel_azul = new javax.swing.JPanel();
        txt_info = new javax.swing.JLabel();
        txt_info1 = new javax.swing.JLabel();
        label_nombre1 = new javax.swing.JLabel();
        label_rol = new javax.swing.JLabel();
        label_cerrarS = new javax.swing.JLabel();
        tarjeta_1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                // Activamos el suavizado de bordes (Anti-aliasing)
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Dibujamos el fondo blanco redondeado
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // 30 es el nivel de redondeo

                // Dibujamos el borde gris muy clarito (opcional, para que resalte)
                g2.setColor(new java.awt.Color(230, 230, 230));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
            }
        };
        txt_info3 = new javax.swing.JLabel();
        txt_info4 = new javax.swing.JLabel();
        txt_info5 = new javax.swing.JLabel();
        circulo1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Color azul muy clarito (como el de la referencia)
                g2.setColor(new java.awt.Color(232, 240, 254)); 

                // Dibujamos el círculo (un óvalo con mismo ancho y alto)
                g2.fillOval(0, 0, getWidth(), getHeight());
            }
        };
        icono_voto = new javax.swing.JLabel();
        tarjeta_2 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                // Activamos el suavizado de bordes (Anti-aliasing)
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Dibujamos el fondo blanco redondeado
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // 30 es el nivel de redondeo

                // Dibujamos el borde gris muy clarito (opcional, para que resalte)
                g2.setColor(new java.awt.Color(230, 230, 230));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
            }
        };
        txt_info6 = new javax.swing.JLabel();
        txt_info7 = new javax.swing.JLabel();
        txt_info8 = new javax.swing.JLabel();
        circulo2 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Color azul muy clarito (como el de la referencia)
                g2.setColor(new java.awt.Color(232, 240, 254)); 

                // Dibujamos el círculo (un óvalo con mismo ancho y alto)
                g2.fillOval(0, 0, getWidth(), getHeight());
            }
        };
        icono_info = new javax.swing.JLabel();
        tarjeta_3 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                // Activamos el suavizado de bordes (Anti-aliasing)
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Dibujamos el fondo blanco redondeado
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // 30 es el nivel de redondeo

                // Dibujamos el borde gris muy clarito (opcional, para que resalte)
                g2.setColor(new java.awt.Color(230, 230, 230));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
            }
        };
        txt_info9 = new javax.swing.JLabel();
        txt_info10 = new javax.swing.JLabel();
        txt_info11 = new javax.swing.JLabel();
        circulo3 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Color azul muy clarito (como el de la referencia)
                g2.setColor(new java.awt.Color(232, 240, 254)); 

                // Dibujamos el círculo (un óvalo con mismo ancho y alto)
                g2.fillOval(0, 0, getWidth(), getHeight());
            }
        };
        icono_perfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_fondo.setMaximumSize(new java.awt.Dimension(1280, 720));
        panel_fondo.setMinimumSize(new java.awt.Dimension(1280, 720));
        panel_fondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        panel_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_azul.setBackground(new java.awt.Color(0, 74, 173));
        panel_azul.setMaximumSize(new java.awt.Dimension(1280, 90));
        panel_azul.setMinimumSize(new java.awt.Dimension(1280, 90));
        panel_azul.setPreferredSize(new java.awt.Dimension(1280, 90));
        panel_azul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_info.setForeground(new java.awt.Color(255, 255, 255));
        txt_info.setText("Sistema de votaciones");
        panel_azul.add(txt_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 203, 32));

        txt_info1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info1.setForeground(new java.awt.Color(255, 255, 255));
        txt_info1.setText("Sistema universitario");
        panel_azul.add(txt_info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        label_nombre1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_nombre1.setForeground(new java.awt.Color(255, 255, 255));
        panel_azul.add(label_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 190, 40));

        label_rol.setForeground(new java.awt.Color(255, 255, 255));
        panel_azul.add(label_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 130, 30));

        label_cerrarS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        label_cerrarS.setForeground(new java.awt.Color(255, 255, 255));
        label_cerrarS.setText("Cerrar sesión");
        panel_azul.add(label_cerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 80, 40));

        panel_fondo.add(panel_azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tarjeta_1.setBackground(new java.awt.Color(255, 255, 255));
        tarjeta_1.setOpaque(false);
        tarjeta_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_info3.setForeground(new java.awt.Color(0, 74, 173));
        txt_info3.setText("VOTAR");
        txt_info3.setToolTipText("");
        tarjeta_1.add(txt_info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        txt_info4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info4.setText("Participa en las votaciones disponibles ");
        tarjeta_1.add(txt_info4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, 30));

        txt_info5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info5.setText("y elige tu opción.");
        tarjeta_1.add(txt_info5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 180, 20));

        circulo1.setOpaque(false);

        icono_voto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout circulo1Layout = new javax.swing.GroupLayout(circulo1);
        circulo1.setLayout(circulo1Layout);
        circulo1Layout.setHorizontalGroup(
            circulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono_voto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        circulo1Layout.setVerticalGroup(
            circulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono_voto, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        tarjeta_1.add(circulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 100));

        panel_fondo.add(tarjeta_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 320, 380));

        tarjeta_2.setBackground(new java.awt.Color(255, 255, 255));
        tarjeta_2.setOpaque(false);
        tarjeta_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_info6.setForeground(new java.awt.Color(0, 74, 173));
        txt_info6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info6.setText("Estado de votación");
        tarjeta_2.add(txt_info6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 30));

        txt_info7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info7.setText("Verifica que ya has votado y consulta");
        tarjeta_2.add(txt_info7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, 20));

        txt_info8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info8.setText("las votaciones disponibles.");
        tarjeta_2.add(txt_info8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 180, -1));

        circulo2.setOpaque(false);

        javax.swing.GroupLayout circulo2Layout = new javax.swing.GroupLayout(circulo2);
        circulo2.setLayout(circulo2Layout);
        circulo2Layout.setHorizontalGroup(
            circulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circulo2Layout.createSequentialGroup()
                .addComponent(icono_info, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        circulo2Layout.setVerticalGroup(
            circulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circulo2Layout.createSequentialGroup()
                .addComponent(icono_info, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tarjeta_2.add(circulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 100));

        panel_fondo.add(tarjeta_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 320, 380));

        tarjeta_3.setBackground(new java.awt.Color(255, 255, 255));
        tarjeta_3.setOpaque(false);
        tarjeta_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_info9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txt_info9.setForeground(new java.awt.Color(0, 74, 173));
        txt_info9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info9.setText("Ver perfil");
        tarjeta_3.add(txt_info9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 30));

        txt_info10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_info10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_info10.setText("Consulta y actualiza tu información");
        tarjeta_3.add(txt_info10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txt_info11.setText("personal y datos de cuenta.");
        tarjeta_3.add(txt_info11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        circulo3.setOpaque(false);

        icono_perfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout circulo3Layout = new javax.swing.GroupLayout(circulo3);
        circulo3.setLayout(circulo3Layout);
        circulo3Layout.setHorizontalGroup(
            circulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        circulo3Layout.setVerticalGroup(
            circulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icono_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        tarjeta_3.add(circulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 100));

        panel_fondo.add(tarjeta_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 320, 380));

        getContentPane().add(panel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel circulo1;
    private javax.swing.JPanel circulo2;
    private javax.swing.JPanel circulo3;
    private javax.swing.JLabel icono_info;
    private javax.swing.JLabel icono_perfil;
    private javax.swing.JLabel icono_voto;
    private javax.swing.JLabel label_cerrarS;
    private javax.swing.JLabel label_nombre1;
    private javax.swing.JLabel label_rol;
    private javax.swing.JPanel panel_azul;
    private javax.swing.JPanel panel_fondo;
    private javax.swing.JPanel tarjeta_1;
    private javax.swing.JPanel tarjeta_2;
    private javax.swing.JPanel tarjeta_3;
    private javax.swing.JLabel txt_info;
    private javax.swing.JLabel txt_info1;
    private javax.swing.JLabel txt_info10;
    private javax.swing.JLabel txt_info11;
    private javax.swing.JLabel txt_info3;
    private javax.swing.JLabel txt_info4;
    private javax.swing.JLabel txt_info5;
    private javax.swing.JLabel txt_info6;
    private javax.swing.JLabel txt_info7;
    private javax.swing.JLabel txt_info8;
    private javax.swing.JLabel txt_info9;
    // End of variables declaration//GEN-END:variables

private ImageIcon cargarIcono(String nombre, int ancho, int alto) {
    String base = System.getProperty("user.dir");

    ImageIcon icono = new ImageIcon(base + "\\" + nombre);

    Image img = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);

    return new ImageIcon(img);
}
private void cargarIconos() {
    icono_voto.setIcon(cargarIcono("voto.png", 100, 100));
    icono_info.setIcon(cargarIcono("info.png", 100, 100));
    icono_perfil.setIcon(cargarIcono("usuario.png", 100, 100));
}
}
