/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.admin;
import java.util.ArrayList;
import config.Conexion;
import gui.menuPrincipal;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.Window;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import util.placeHolderJtext;

/**
 *
 * @author DISTRIEMPAQUES
 */
public class PanelGestionVotaciones extends javax.swing.JPanel {
    String rutaFoto = "";
    private String nombre;
    public static ArrayList<Integer> usuariosQueVotaron = new ArrayList<>();

    /**
     * Creates new form PanelGestionVotaciones
     */
    public PanelGestionVotaciones() {
        initComponents();
        this.nombre = nombre;
        
         placeHolderJtext.addPlaceholder(caja_nombre, "Nombre completo");
        placeHolderJtext.addPlaceholder(caja_titulo, "Titlo de la eleccion");
        placeHolderJtext.addPlaceholder(caja_descripcion, "UEscriba aquí la descripción de la elección");
        placeHolderJtext.addPlaceholder(caja_carrera, "carrera");
        placeHolderJtext.addPlaceholder(caja_carrera, "carrera");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                // Activamos el suavizado de bordes (Anti-aliasing)
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

                // Dibujamos el fondo blanco redondeado
                g2.setColor(java.awt.Color.WHITE);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 30, 30); // 30 es el nivel de redondeo

                // Dibujamos el borde gris muy clarito (opcional, para que resalte)
                g2.setColor(new java.awt.Color(230, 230, 230));
                g2.drawRoundRect(0, 0, getWidth() - 1, getHeight() - 1, 30, 30);
            }
        };
        roundedPanel3 = new gui.components.RoundedPanel();
        lbl_desactivar = new javax.swing.JLabel();
        roundedPanel1 = new gui.components.RoundedPanel();
        lbl_editar = new javax.swing.JLabel();
        roundedPanel4 = new gui.components.RoundedPanel();
        lbl_entrar = new javax.swing.JLabel();
        roundedPanel5 = new gui.components.RoundedPanel();
        lbl_activar = new javax.swing.JLabel();
        panel_dinamico = new gui.components.RoundedPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        caja_descripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        caja_ffin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caja_titulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        caja_finicio = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        caja_nombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        caja_carrera = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        caja_numero = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        caja_id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        caja_idc = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        boton_volver = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        setMaximumSize(new java.awt.Dimension(900, 580));
        setMinimumSize(new java.awt.Dimension(900, 580));
        setPreferredSize(new java.awt.Dimension(900, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Gestión votantes.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 12, -1, 21));

        jLabel2.setText("Seleccione una opción para administrar las votaciones.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        lbl_desactivar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_desactivar.setText("Desac votación.");
        lbl_desactivar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_desactivar)
                .addGap(27, 27, 27))
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_desactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_editar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_editar.setText("Editar votación.");
        lbl_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrada(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_editar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_entrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_entrar.setText("Crear votación.");
        lbl_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrada(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salida(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_entrar)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_activar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_activar.setText("Activar votación.");
        lbl_activar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_activar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_activar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundedPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundedPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundedPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(roundedPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(roundedPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 490));

        panel_dinamico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Crear votación.");
        panel_dinamico.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 187, 36));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Título");
        jLabel4.setToolTipText("");
        panel_dinamico.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 50, -1));
        panel_dinamico.add(caja_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 250, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Descripción");
        panel_dinamico.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        panel_dinamico.add(caja_ffin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 250, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Fecha fin");
        panel_dinamico.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 20));
        panel_dinamico.add(caja_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 52, 290, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("Fecha inicio");
        panel_dinamico.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));
        panel_dinamico.add(caja_finicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 250, 40));
        panel_dinamico.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 200, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Agregar candidato");
        panel_dinamico.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));
        panel_dinamico.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 590, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("Foto");
        panel_dinamico.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 40, 30));

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_dinamico.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Nombre completo");
        panel_dinamico.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));
        panel_dinamico.add(caja_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 180, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Carrera");
        panel_dinamico.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));
        panel_dinamico.add(caja_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 130, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("N. tarjeton");
        panel_dinamico.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 80, 20));
        panel_dinamico.add(caja_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 100, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar candidato");
        jButton2.setActionCommand(" ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_dinamico.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, 30));
        panel_dinamico.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 250, 10));

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Vaciar");
        panel_dinamico.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 120, 40));

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Crear votación");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel_dinamico.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 140, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setText("ID elección");
        panel_dinamico.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        caja_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_idActionPerformed(evt);
            }
        });
        panel_dinamico.add(caja_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 170, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setText("Id candidato");
        panel_dinamico.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));
        panel_dinamico.add(caja_idc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 110, 30));
        panel_dinamico.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 160, 130));

        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("Preview imagen seleccionada");
        panel_dinamico.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        add(panel_dinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 590, 510));

        boton_volver.setBackground(new java.awt.Color(0, 74, 173));
        boton_volver.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        boton_volver.setForeground(new java.awt.Color(255, 255, 255));
        boton_volver.setText("←");
        boton_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverActionPerformed(evt);
            }
        });
        add(boton_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void salida(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salida
        // TODO add your handling code here:
        lbl_activar.setBackground(new Color(0,0,0));
        lbl_editar.setBackground(new Color(0,0,0));
        lbl_desactivar.setBackground(new Color(0,0,0));
        lbl_entrar.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_salida

    private void entrada(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrada
        // TODO add your handling code here:
        lbl_activar.setBackground(new Color(33,150,243));
        lbl_editar.setBackground(new Color(33,150,243));
        lbl_desactivar.setBackground(new Color(33,150,243));
        lbl_entrar.setBackground(new Color(33,150,243));
    }//GEN-LAST:event_entrada

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
    int resultado = chooser.showOpenDialog(this);
    if(resultado == JFileChooser.APPROVE_OPTION){
    File archivo = chooser.getSelectedFile();
    rutaFoto = archivo.getAbsolutePath();
    ImageIcon icon =
            new ImageIcon(rutaFoto);
    Image img =
            icon.getImage().getScaledInstance(
                    120,
                    120,
                    Image.SCALE_SMOOTH
            );
    lblFoto.setIcon(
            new ImageIcon(img)
    );
        chooser.showOpenDialog(this);
        FileNameExtensionFilter filtro =new FileNameExtensionFilter( "Imágenes", "jpg", "png", "jpeg");

chooser.setFileFilter(filtro);
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void caja_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_idActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
    Connection con1 = Conexion.conectar();

    String idTexto = caja_id.getText().trim();
    if (idTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El ID no puede estar vacío");
        return;
    }

    int id = Integer.parseInt(idTexto);

    String sql = "INSERT INTO elecciones (id_eleccion, nombre, fecha_inicio, fecha_fin, estado_activa, descripcion) VALUES (?, ?, ?, ?, ?, ?)";

    PreparedStatement ps = con1.prepareStatement(sql);

    ps.setInt(1, id);
    ps.setString(2, caja_titulo.getText());
    ps.setString(3, caja_finicio.getText());
    ps.setString(4, caja_ffin.getText());
    ps.setBoolean(5, false);
    ps.setString(6, caja_descripcion.getText());

    ps.executeUpdate();

    JOptionPane.showMessageDialog(this, "Elección agregada correctamente");

    caja_titulo.setText("");
    caja_finicio.setText("");
    caja_ffin.setText("");
    caja_idc.setText("");
    caja_descripcion.setText("");

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "El ID debe ser un número válido");
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {

        Connection con =
                Conexion.conectar();

        String sql =
        "INSERT INTO candidatos "
        + "(id_candidato, id_eleccion, foto, carrera, nombre) "
        + "VALUES (?, ?, ?, ?,?)";

            PreparedStatement ps = con.prepareStatement(sql);

            ps.setInt(1, Integer.parseInt(caja_idc.getText()));
            ps.setInt(2, Integer.parseInt(caja_id.getText()));
            ps.setString(3, rutaFoto);
            ps.setString(4, caja_carrera.getText());
            ps.setString(5, caja_nombre.getText());
        
        ps.executeUpdate();

        JOptionPane.showMessageDialog( this, "Candidato agregado correctamente");
        caja_nombre.setText("");
        caja_carrera.setText("");
        caja_idc.setText("");
        lblFoto.setIcon(null);
        rutaFoto = "";

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,"Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void boton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    Window ventana = SwingUtilities.getWindowAncestor(this);

    if (ventana instanceof menuAdmin admin) {
        admin.restaurarMenuAdm();
    }
    }//GEN-LAST:event_boton_volverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_volver;
    private javax.swing.JTextField caja_carrera;
    private javax.swing.JTextField caja_descripcion;
    private javax.swing.JTextField caja_ffin;
    private javax.swing.JTextField caja_finicio;
    private javax.swing.JTextField caja_id;
    private javax.swing.JTextField caja_idc;
    private javax.swing.JTextField caja_nombre;
    private javax.swing.JTextField caja_numero;
    private javax.swing.JTextField caja_titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lbl_activar;
    private javax.swing.JLabel lbl_desactivar;
    private javax.swing.JLabel lbl_editar;
    private javax.swing.JLabel lbl_entrar;
    private gui.components.RoundedPanel panel_dinamico;
    private gui.components.RoundedPanel roundedPanel1;
    private gui.components.RoundedPanel roundedPanel3;
    private gui.components.RoundedPanel roundedPanel4;
    private gui.components.RoundedPanel roundedPanel5;
    // End of variables declaration//GEN-END:variables

    private void mostrarPropuestas(String nombre) {

    String propuestas =
        util.Propuestasloader.obtenerPropuestas(nombre);

    javax.swing.JOptionPane.showMessageDialog(
        null,
        propuestas,
        "Propuestas de " + nombre,
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
}
}
